import { defaultLanguages, type ZudokuConfig } from "zudoku";
import Badge from "./src/components/Badge";
import { CardGrid, LinkCard } from "./src/components/LinkCards";
import ZoomableImage from "./src/components/ZoomableImage";
import { openGraphPlugin } from "./src/plugins/openGraph";

const config: ZudokuConfig = {
  syntaxHighlighting: {
    languages: [...defaultLanguages, "php"],
  },
  defaults: {
    apis: {
      // Show the Authentification section in specifications in the API Playground
      disableSecurity: false,
    }
  },
  site: {
    title: "DaLin",
    logo: {
      src: { light: "/dalin-logo-light.png", dark: "/dalin-logo-dark.png" },
      alt: "DaLin dokumentace",
      width: "110px",
    },
  },
  metadata: {
    title: "%s | DaLin dokumentace",
    defaultTitle: "DaLin dokumentace",
    description:
      "DaLin — klubový informační systém správy orientačních sportů",
    favicon: "/favicon.ico",
  },
  theme: {
    light: {
      primary: "#c2410c",
      primaryForeground: "#ffffff",
      ring: "#c2410c",
    },
    dark: {
      primary: "#ea580c",
      primaryForeground: "#ffffff",
      ring: "#ea580c",
    },
    fonts: {
      sans: {
        url: "https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap",
        fontFamily: "'Poppins', system-ui, sans-serif",
      },
    },
  },
  apis: [
    {
      type: "file",
      // Generated by Scribe in the DaLin app repo (`sail artisan scribe:generate`,
      // output: storage/app/scribe/openapi.yaml) and synced here by /update-docs-zudoku.
      input: "./apis/openapi.yaml",
      path: "/api",
    },
    {
      type: "file",
      // Neoficiální OpenAPI specifikace ORIS API, viz apis/oris-openapi.yaml.
      input: "./apis/oris-openapi.yaml",
      path: "/oris-api",
    },
  ],
  navigation: [
    {
      type: "category",
      label: "Nápověda",
      items: [
        {
          type: "category",
          label: "Aplikace",
          icon: "sparkles",
          collapsible: false,
          items: [
            { type: "doc", file: "napoveda/index", label: "Jsem tu nový" },
            {
              type: "doc",
              file: "napoveda/usnadneni-procesu",
              label: "Usnadnění procesů",
            },
          ],
        },
        {
          type: "category",
          label: "Stránky",
          icon: "layout-dashboard",
          collapsible: false,
          items: [
            {
              type: "doc",
              file: "napoveda/stranka-zavody-akce",
              label: "Závod/Akce",
            },
            {
              type: "doc",
              file: "napoveda/stranka-zavod-detail",
              label: "Detail akce",
            },
            {
              type: "doc",
              file: "napoveda/stranka-prihlasky",
              label: "Přihlášky na akce",
            },
            {
              type: "doc",
              file: "napoveda/stranka-uzivatelska-nastaveni",
              label: "Uživatelská nastavení",
            },
            { type: "doc", file: "napoveda/stranka-finance", label: "Finance" },
            {
              type: "doc",
              file: "napoveda/stranka-registrace",
              label: "Registrace",
            },
            {
              type: "doc",
              file: "napoveda/member-race-profile",
              label: "Závodní profil",
            },
            { type: "doc", file: "napoveda/trziste", label: "Tržiště" },
          ],
        },
        {
          type: "category",
          label: "Jak na to",
          icon: "circle-help",
          collapsible: false,
          items: [
            {
              type: "doc",
              file: "napoveda/role-v-aplikaci",
              label: "Role v aplikaci",
            },
            {
              type: "category",
              label: "Člen",
              items: [
                {
                  type: "doc",
                  file: "napoveda/jak-se-prihlasit-na-oris-zavod",
                  label: "Přihlásit na závod ORISu",
                },
                {
                  type: "doc",
                  file: "napoveda/jak-se-odhlasit-ze-zavodu",
                  label: "Odhlásit ze závodu",
                },
                {
                  type: "doc",
                  file: "napoveda/jak-si-nastavit-notitifikace",
                  label: "Nastavení notifikací",
                },
              ],
            },
            {
              type: "category",
              label: "Správce závodů",
              items: [
                {
                  type: "doc",
                  file: "napoveda/jak-pridat-zavod",
                  label: "Přidat závod",
                },
              ],
            },
            {
              type: "category",
              label: "Organizátor závodů",
              items: [
                {
                  type: "doc",
                  file: "napoveda/jak-poslat-upozorneni-prihlasenym-zavodnikum",
                  label: "Zaslat upozornění",
                },
                {
                  type: "doc",
                  file: "napoveda/jak-exportovat-data-o-zavodu",
                  label: "Export dat o závodu",
                },
              ],
            },
            {
              type: "category",
              label: "Finančník",
              items: [
                {
                  type: "doc",
                  file: "napoveda/bankovni-vypis",
                  label: "Bankovní výpis",
                },
                {
                  type: "doc",
                  file: "napoveda/jednoduche-cestovni-vyrovnani",
                  label: "Cestovní vyrovnání",
                },
                {
                  type: "doc",
                  file: "napoveda/stranka-finance-clenu",
                  label: "Finance členů",
                },
              ],
            },
            {
              type: "category",
              label: "Admin klubu",
              items: [
                {
                  type: "doc",
                  file: "napoveda/jak-zalozit-uzivatele",
                  label: "Nový uživatel",
                },
                {
                  type: "doc",
                  file: "napoveda/jak-pridat-uzivateli-registraci",
                  label: "Nová registrace",
                },
                {
                  type: "doc",
                  file: "napoveda/odeslane-emaily",
                  label: "Odeslané e-maily",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Instalace",
      items: [
        { type: "doc", file: "install/index", label: "Úvod" },
        {
          type: "doc",
          file: "install/site-config",
          label: "Konfigurace stránky",
        },
        {
          type: "doc",
          file: "install/bank-connector",
          label: "Napojení na banku",
        },
      ],
    },
    {
      type: "category",
      label: "Novinky",
      items: [
        { type: "doc", file: "changelog/index", label: "Verze 12.x" },
        { type: "doc", file: "changelog/v11", label: "Verze 11.x" },
        { type: "doc", file: "changelog/v10", label: "Verze 10.x" },
        {
          type: "link",
          to: "https://github.com/jZejda/dalin/releases",
          label: "GitHub releases",
          icon: "external-link",
        },
      ],
    },
    {
      type: "category",
      label: "O projektu",
      items: [
        { type: "doc", file: "develop/index", label: "Úvod" },
        {
          type: "doc",
          file: "develop/development-environment",
          label: "Prostředí",
        },
        {
          type: "doc",
          file: "develop/localization",
          label: "Lokalizace CZ/EN",
        },
        {
          type: "doc",
          file: "develop/marketplace-module",
          label: "Modul Tržiště",
        },
        {
          type: "doc",
          file: "develop/bank-module",
          label: "Modul Napojení na banku",
        },
      ],
    },
    {
      type: "link",
      to: "/api",
      label: "API",
      icon: "globe",
    },
    {
      type: "link",
      to: "/oris-api",
      label: "ORIS API",
      icon: "globe",
    },
  ],
  mdx: {
    components: {
      img: ZoomableImage,
      Badge,
      CardGrid,
      LinkCard,
    },
  },
  search: {
    type: "pagefind",
    maxSubResults: 3,
  },
  canonicalUrlOrigin: "https://docs.dalin.cz",
  plugins: [
    openGraphPlugin({
      origin: "https://docs.dalin.cz",
      siteName: "DaLin dokumentace",
      locale: "cs_CZ",
      image: "/og.png",
    }),
  ],
  redirects: [
    { from: "/", to: "/index" },
    // old VitePress section roots
    { from: "/napoveda", to: "/napoveda/index" },
    { from: "/install", to: "/install/index" },
    { from: "/changelog", to: "/changelog/index" },
    { from: "/develop", to: "/develop/index" },
  ],
};

export default config;
