import { defaultLanguages, type ZudokuConfig } from "zudoku";
import Badge from "./src/components/Badge";
import { CardGrid, LinkCard } from "./src/components/LinkCards";
import ZoomableImage from "./src/components/ZoomableImage";
import { openGraphPlugin } from "./src/plugins/openGraph";

const config: ZudokuConfig = {
  syntaxHighlighting: {
    languages: [...defaultLanguages, "php"],
  },
  defaults: {
    apis: {
      // Show the Authentification section in specifications in the API Playground
      disableSecurity: false,
    }
  },
  site: {
    title: "DaLin",
    logo: {
      src: { light: "/dalin-logo-light.svg", dark: "/dalin-logo-dark.svg" },
      alt: "DaLin dokumentace",
      width: "110px",
    },
  },
  metadata: {
    title: "%s | DaLin dokumentace",
    defaultTitle: "DaLin dokumentace",
    description:
      "DaLin — klubový informační systém správy orientačních sportů",
    favicon: "/favicon.ico",
  },
  theme: {
    light: {
      primary: "#c2410c",
      primaryForeground: "#ffffff",
      ring: "#c2410c",
    },
    dark: {
      primary: "#ea580c",
      primaryForeground: "#ffffff",
      ring: "#ea580c",
    },
    fonts: {
      sans: {
        url: "https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap",
        fontFamily: "'Poppins', system-ui, sans-serif",
      },
    },
  },
  apis: [
    {
      type: "file",
      // Generated by Scribe in the DaLin app repo (`sail artisan scribe:generate`,
      // output: storage/app/scribe/openapi.yaml) and synced here by /update-docs-zudoku.
      input: "./apis/openapi.yaml",
      path: "/api",
    },
    {
      type: "file",
      // Neoficiální OpenAPI specifikace ORIS API, viz apis/oris-openapi.yaml.
      input: "./apis/oris-openapi.yaml",
      path: "/oris-api",
    },
  ],
  navigation: [
    // Maps pages/index.mdx directly to "/" (its file-based route would
    // otherwise be "/index"), so the client router matches the root path
    // on hydration instead of falling through to the 404 page.
    { type: "doc", file: "index", path: "/", display: "hide" },
    {
      type: "category",
      label: "Nápověda",
      items: [
        {
          type: "category",
          label: "Aplikace",
          icon: "sparkles",
          collapsible: false,
          items: [
            { type: "doc", file: "napoveda/index", label: "Jsem tu nový", icon: "sparkles" },
            {
              type: "doc",
              file: "napoveda/prechod-na-v13",
              label: "Přechod na verzi 13",
              icon: "rocket",
            },
            {
              type: "doc",
              file: "napoveda/ovladani-aplikace",
              label: "Jak používat aplikaci",
              icon: "mouse-pointer-click",
            },
            {
              type: "doc",
              file: "napoveda/usnadneni-procesu",
              label: "Usnadnění procesů",
              icon: "zap",
            },
            {
              type: "doc",
              file: "napoveda/role-v-aplikaci",
              label: "Role v aplikaci",
              icon: "shield-check",
            },
          ],
        },
        // Od tohoto místa dál kopíruje strukturu skupin z levého menu administrace
        // Dalinu (viz app/Providers/Filament/AdminPanelProvider.php v backend repu) —
        // nerozdělujeme podle rolí (konkrétní oprávnění si admin klubu může měnit),
        // jen podle toho, kde se to v aplikaci fyzicky nachází.
        {
          type: "category",
          label: "Závody / události",
          icon: "calendar",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              file: "napoveda/stranka-zavody-akce",
              label: "Přehled závodů / akcí",
              icon: "list",
            },
            {
              type: "doc",
              file: "napoveda/stranka-zavod-detail",
              label: "Detail závodu",
              icon: "file-text",
            },
            {
              type: "doc",
              file: "napoveda/jak-pridat-zavod",
              label: "Přidat závod z ORISu",
              icon: "download",
            },
            {
              type: "doc",
              file: "napoveda/jak-poslat-upozorneni-prihlasenym-zavodnikum",
              label: "Poslat upozornění přihlášeným",
              icon: "mail",
            },
            {
              type: "doc",
              file: "napoveda/jak-exportovat-data-o-zavodu",
              label: "Export dat o závodu",
              icon: "file-down",
            },
          ],
        },
        {
          type: "category",
          label: "Registrace",
          icon: "users-round",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              file: "napoveda/stranka-registrace",
              label: "Stránka registrace",
              icon: "list",
            },
            {
              type: "doc",
              file: "napoveda/member-race-profile",
              label: "Závodní profil",
              icon: "id-card",
            },
            {
              type: "doc",
              file: "napoveda/jak-pridat-uzivateli-registraci",
              label: "Přidat uživateli registraci",
              icon: "user-plus",
            },
          ],
        },
        {
          type: "category",
          label: "Tržiště",
          icon: "shopping-bag",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "doc", file: "napoveda/trziste", label: "Tržiště", icon: "shopping-bag" },
          ],
        },
        {
          type: "category",
          label: "Uživatel",
          icon: "user",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Přihlášky",
              icon: "flag",
              items: [
                {
                  type: "doc",
                  file: "napoveda/stranka-prihlasky",
                  label: "Přihlášky na akce",
                  icon: "list",
                },
                {
                  type: "doc",
                  file: "napoveda/jak-se-prihlasit-na-oris-zavod",
                  label: "Přihlásit na závod ORISu",
                  icon: "log-in",
                },
                {
                  type: "doc",
                  file: "napoveda/jak-se-odhlasit-ze-zavodu",
                  label: "Odhlásit ze závodu",
                  icon: "log-out",
                },
              ],
            },
            {
              type: "category",
              label: "Můj kredit",
              icon: "banknote",
              items: [
                {
                  type: "doc",
                  file: "napoveda/stranka-finance",
                  label: "Finance",
                  icon: "wallet",
                },
              ],
            },
            {
              type: "category",
              label: "Ostatní",
              icon: "user-cog",
              items: [
                {
                  type: "doc",
                  file: "napoveda/stranka-uzivatelska-nastaveni",
                  label: "Uživatelská nastavení",
                  icon: "settings-2",
                },
                {
                  type: "doc",
                  file: "napoveda/jak-si-nastavit-notitifikace",
                  label: "Nastavení notifikací",
                  icon: "bell",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Správa financí",
          icon: "wallet",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              file: "napoveda/stranka-finance-clenu",
              label: "Finance členů",
              icon: "scale",
            },
            {
              type: "doc",
              file: "napoveda/jednoduche-cestovni-vyrovnani",
              label: "Vyúčtování akcí (cestovní vyrovnání)",
              icon: "banknote",
            },
            {
              type: "doc",
              file: "napoveda/bankovni-vypis",
              label: "Bankovní výpis",
              icon: "qr-code",
            },
          ],
        },
        {
          type: "category",
          label: "Obsah",
          icon: "folder-open",
          collapsible: true,
          collapsed: true,
          items: [
            { type: "doc", file: "napoveda/sprava-novinek", label: "Novinky", icon: "newspaper" },
            {
              type: "doc",
              file: "napoveda/sprava-stranek",
              label: "Stránky",
              icon: "file-text",
            },
            {
              type: "doc",
              file: "napoveda/kategorie-obsahu",
              label: "Kategorie obsahu",
              icon: "tag",
            },
          ],
        },
        {
          type: "category",
          label: "Nastavení",
          icon: "settings",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              file: "napoveda/jak-zalozit-uzivatele",
              label: "Uživatelé",
              icon: "users",
            },
            {
              type: "doc",
              file: "napoveda/nastaveni-aplikace",
              label: "Nastavení",
              icon: "sliders-horizontal",
            },
            {
              type: "doc",
              file: "napoveda/nastaveni-klubu",
              label: "Nastavení klubu",
              icon: "id-card",
            },
            {
              type: "doc",
              file: "napoveda/bankovni-napojeni",
              label: "Bankovní napojení",
              icon: "landmark",
            },
            {
              type: "doc",
              file: "napoveda/mapove-ikony",
              label: "Ikony v mapě",
              icon: "palette",
            },
            {
              type: "doc",
              file: "napoveda/klubova-vozidla",
              label: "Klubová vozidla",
              icon: "truck",
            },
            {
              type: "doc",
              file: "napoveda/odeslane-emaily",
              label: "Odeslané e-maily",
              icon: "mail",
            },
            {
              type: "doc",
              file: "napoveda/role-v-aplikaci",
              label: "Role",
              icon: "shield",
            },
            { type: "doc", file: "napoveda/kluby", label: "Kluby", icon: "building" },
            {
              type: "doc",
              file: "napoveda/vystupy-pro-poradani",
              label: "Výstupy pro pořádání",
              icon: "list-tree",
            },
            {
              type: "doc",
              file: "napoveda/definice-kategorii",
              label: "Definice kategorií",
              icon: "layers",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Instalace",
      items: [
        { type: "doc", file: "install/index", label: "Úvod" },
        {
          type: "doc",
          file: "install/site-config",
          label: "Konfigurace stránky",
        },
        {
          type: "doc",
          file: "install/bank-connector",
          label: "Napojení na banku",
        },
      ],
    },
    {
      type: "category",
      label: "Novinky",
      items: [
        { type: "doc", file: "changelog/index", label: "Verze 13.x" },
        { type: "doc", file: "changelog/v12", label: "Verze 12.x" },
        { type: "doc", file: "changelog/v11", label: "Verze 11.x" },
        { type: "doc", file: "changelog/v10", label: "Verze 10.x" },
        {
          type: "link",
          to: "https://github.com/jZejda/dalin/releases",
          label: "GitHub releases",
          icon: "external-link",
        },
      ],
    },
    {
      type: "category",
      label: "O projektu",
      items: [
        { type: "doc", file: "develop/index", label: "Úvod" },
        {
          type: "doc",
          file: "develop/development-environment",
          label: "Prostředí",
        },
        {
          type: "doc",
          file: "develop/localization",
          label: "Lokalizace CZ/EN",
        },
        {
          type: "doc",
          file: "develop/marketplace-module",
          label: "Modul Tržiště",
        },
        {
          type: "doc",
          file: "develop/bank-module",
          label: "Modul Napojení na banku",
        },
      ],
    },
    {
      type: "link",
      to: "/api",
      label: "API",
      icon: "globe",
    },
    {
      type: "link",
      to: "/oris-api",
      label: "ORIS API",
      icon: "globe",
    },
  ],
  mdx: {
    components: {
      img: ZoomableImage,
      Badge,
      CardGrid,
      LinkCard,
    },
  },
  search: {
    type: "pagefind",
    maxSubResults: 3,
  },
  canonicalUrlOrigin: "https://docs.dalin.cz",
  plugins: [
    openGraphPlugin({
      origin: "https://docs.dalin.cz",
      siteName: "DaLin dokumentace",
      locale: "cs_CZ",
      image: "/og.png",
    }),
  ],
  redirects: [
    // old VitePress section roots
    { from: "/napoveda", to: "/napoveda/index" },
    { from: "/install", to: "/install/index" },
    { from: "/changelog", to: "/changelog/index" },
    { from: "/develop", to: "/develop/index" },
  ],
};

export default config;
